=== SalsaAddict/emusicality2022/src/schema/iBreakdown.json
{
    "$ref": "#/definitions/IBreakdown",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "IBreakdown": {
            "additionalProperties": false,
            "properties": {
                "beatsPerMeasure": {
                    "title": "beatsPerMeasure",
                    "type": "number"
                },
                "lag": {
                    "title": "lag",
                    "type": "number"
                },
                "sections": {
                    "items": {
                        "$ref": "#/definitions/ISection"
                    },
                    "title": "sections",
                    "type": "array"
                },
                "tracks": {
                    "$ref": "#/definitions/ITracks",
                    "title": "tracks"
                },
                "trim": {
                    "title": "trim",
                    "type": "number"
                }
            },
            "required": [
                "beatsPerMeasure",
                "sections",
                "tracks"
            ],
            "title": "IBreakdown",
            "type": "object"
        },
        "IMeasure": {
            "additionalProperties": false,
            "properties": {
                "beats": {
                    "title": "beats",
                    "type": "number"
                },
                "offset": {
                    "title": "offset",
                    "type": "number"
                },
                "structure": {
                    "title": "structure",
                    "type": "string"
                }
            },
            "title": "IMeasure",
            "type": "object"
        },
        "IPhrase": {
            "anyOf": [
                {
                    "items": {
                        "anyOf": [
                            {
                                "$ref": "#/definitions/IMeasure"
                            },
                            {
                                "type": [
                                    "string",
                                    "number"
                                ]
                            }
                        ]
                    },
                    "type": "array"
                },
                {
                    "type": "number"
                }
            ],
            "title": "IPhrase"
        },
        "ISection": {
            "additionalProperties": false,
            "properties": {
                "phrases": {
                    "items": {
                        "$ref": "#/definitions/IPhrase"
                    },
                    "title": "phrases",
                    "type": "array"
                },
                "structure": {
                    "title": "structure",
                    "type": "string"
                },
                "title": {
                    "title": "title",
                    "type": "string"
                }
            },
            "required": [
                "phrases",
                "title"
            ],
            "title": "ISection",
            "type": "object"
        },
        "ITrack": {
            "additionalProperties": false,
            "properties": {
                "groups": {
                    "anyOf": [
                        {
                            "items": {
                                "type": "string"
                            },
                            "type": "array"
                        },
                        {
                            "type": "string"
                        }
                    ],
                    "title": "groups"
                },
                "title": {
                    "title": "title",
                    "type": "string"
                },
                "trim": {
                    "title": "trim",
                    "type": "number"
                }
            },
            "required": [
                "title"
            ],
            "title": "ITrack",
            "type": "object"
        },
        "ITrackType": {
            "anyOf": [
                {
                    "$ref": "#/definitions/ITrack"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ITrackType"
        },
        "ITracks": {
            "anyOf": [
                {
                    "items": {
                        "$ref": "#/definitions/ITrackType"
                    },
                    "type": "array"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ITracks"
        }
    }
}

=== SalsaAddict/emusicality2022/src/assets/songs/oldtownroad/breakdown.json
{
  "trim": 1.9,
  "beatsPerMeasure": 8,
  "tracks": [
    "Vocals",
    { "title": "Percussion", "groups": "Rhythm" },
    {
      "title": "Bass Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Rhythm Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Lead Guitar",
      "groups": "Guitars"
    },
    {
      "title": "Country Guitar",
      "groups": "Guitars"
    },
    "Synth",
    "Strings &amp; Pads"
  ],
  "sections": [
    {
      "title": "Intro",
      "structure": "Derecho",
      "phrases": [4]
    },
    {
      "title": "Mambo",
      "structure": "Majao",
      "phrases": [4]
    },
    {
      "title": "Interlude",
      "phrases": [4]
    },
    { "title": "Chorus", "phrases": [4] },
    { "title": "Verse", "structure": "Derecho", "phrases": [4] },
    { "title": "Pre Chorus", "structure": "Derecho", "phrases": [4] },
    { "title": "Chorus", "structure": "Trap", "phrases": [4] },
    { "title": "Verse", "phrases": [4] },
    { "title": "Pre Chorus", "structure": "Derecho", "phrases": [4] },
    {
      "title": "Bridge",
      "structure": "Derecho",
      "phrases": [4, ["Dembow", 8, 8, 8]]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [4, ["Trap", 8, 8, 8]]
    }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/delmar/breakdown.json
{
  "trim": 0,
  "beatsPerMeasure": 8,
  "tracks": [
    "Vocals",
    { "title": "Bongo &amp; Gu&iuml;ra", "groups": ["Percussion", "Rhythm"] },
    { "title": "Kick Drum", "groups": ["Percussion", "Rhythm"] },
    { "title": "Bass", "groups": ["Guitars", "Rhythm"] },
    { "title": "Segunda", "groups": ["Guitars", "Rhythm"] },
    { "title": "Requinto", "groups": ["Guitars"] },
    "Synths &amp; Pads"
  ],
  "sections": [
    { "title": "Intro", "phrases": [[4], 4] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4, 4] },
    { "title": "Verse", "structure": "Derecho", "phrases": [4] },
    { "title": "Pre-Chorus", "phrases": [2, ["Majao", 8, 8, 8]] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4, 4] },
    { "title": "Mambo", "structure": "Majao", "phrases": [4] },
    { "title": "Interlude", "phrases": [4] },
    { "title": "Bridge", "structure": "Majao", "phrases": [4] },
    { "title": "Chorus", "phrases": [["Breakdown", 8], ["Majao", 8], 4] },
    { "title": "Mambo", "structure": "Majao", "phrases": [4] },
    { "title": "Outro", "phrases": [4] }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/palopalacampana/breakdown.json
{
  "lag": 0.48,
  "trim": 0,
  "beatsPerMeasure": 8,
  "tracks": "5B0gFiehvP8K3eOwk2nZ9s",
  "sections": [
    {
      "title": "Intro",
      "structure": "Salsa",
      "phrases": [4, 4, 1]
    },
    {
      "title": "Bridge",
      "structure": "Oriza",
      "phrases": [4]
    },
    {
      "title": "Verse",
      "structure": "Salsa",
      "phrases": [4, 4]
    },
    {
      "title": "Bridge",
      "structure": "Oriza",
      "phrases": [4]
    },
    {
      "title": "Verse",
      "structure": "Salsa",
      "phrases": [4, 4]
    },
    {
      "title": "Bridge",
      "phrases": [
        ["Afro", 8],
        [{}, 8]
      ]
    },
    {
      "title": "Montuno",
      "structure": "Coro-Pregón",
      "phrases": [4, 4]
    },
    {
      "title": "Montuno",
      "structure": "Coro-Pregón",
      "phrases": [4, 4]
    },
    {
      "title": "Mambo",
      "structure": "Piano Montuno",
      "phrases": [4, 4]
    },
    {
      "title": "Mambo",
      "structure": "Horns/Moñas",
      "phrases": [2, 2, 2, 2]
    },
    {
      "title": "Solo",
      "structure": "Campana Solo",
      "phrases": [4, 4]
    },
    {
      "title": "Solo",
      "structure": "Campana",
      "phrases": [8]
    },
    {
      "title": "Mambo",
      "structure": "Coro",
      "phrases": [2, 2, 2, 2]
    },
    {
      "title": "Montuno",
      "structure": "Coro-Pregón",
      "phrases": [2, 2, 2, 2]
    },
    {
      "title": "Montuno",
      "structure": "Coro-Pregón",
      "phrases": [2, 2, 2, 2]
    },
    {
      "title": "Coda",
      "structure": "Oriza",
      "phrases": [4, 4]
    }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/desnudate/breakdown.json
{
  "trim": 1.85,
  "beatsPerMeasure": 8,
  "tracks": [
    "Vocals",
    {
      "title": "Bongos",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Gu&iuml;ra",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Bass Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Rhythm Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Lead Guitar",
      "groups": "Guitars"
    },
    "Synth &amp; Strings"
  ],
  "sections": [
    { "title": "Intro", "phrases": [4] },
    { "title": "Verse", "structure": "Derecho", "phrases": [4] },
    { "title": "Pre Chorus", "structure": "Derecho", "phrases": [4] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4, 4] },
    { "title": "Interlude", "phrases": [2] },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4]
    },
    {
      "title": "Pre Chorus",
      "structure": "Derecho",
      "phrases": [[8, 8, 8, 8, 4]]
    },
    { "title": "Chorus", "structure": "Majao", "phrases": [4, 4] },
    { "title": "Mambo", "structure": "Majao", "phrases": [[8, 8, 8, 8, 4]] },
    { "title": "Pre Chorus", "structure": "Derecho", "phrases": [4] },
    {
      "title": "Chorus/Outro",
      "structure": "Breakdown",
      "phrases": [4, ["Acapella", 8, 8, 8]]
    }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/ultimabotella/breakdown.json
{
  "lag": 2.75,
  "trim": 0,
  "beatsPerMeasure": 8,
  "tracks": "24ifSHF1A6bIiFB6LB47gz",
  "sections": [
    {
      "title": "Intro",
      "phrases": [
        [8, 8],
        [8, 8]
      ]
    },
    {
      "title": "Mambo",
      "structure": "Derecho",
      "phrases": [4, [4]]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4, 4]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [4, 4]
    },
    {
      "title": "Mambo",
      "phrases": [2, ["Derecho", 8, 8, 8]]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4, 4]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [4, [8, 8, 8, 8, 4]]
    },
    {
      "title": "Bridge",
      "phrases": [["Derecho", 8, 8, 8], ["Majao", 8], 2]
    },
    {
      "title": "Interlude",
      "phrases": [2]
    },
    {
      "title": "Outro",
      "phrases": [2, 2, 2, 2, 2]
    }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/suegra/breakdown.json
{
  "lag": 5.95,
  "trim": 0,
  "beatsPerMeasure": 8,
  "tracks": [
    { "title": "Vocals", "groups": ["Acapella"] },
    {
      "title": "Bongo &amp; Gu&iuml;ra",
      "groups": ["Percussion", "Instrumental"]
    },
    { "title": "Bass Guitar", "groups": ["Guitars", "Instrumental"] },
    {
      "title": "Lead &amp; Rhythm Guitars",
      "groups": ["Guitars", "Instrumental"]
    }
  ],
  "sections": [
    {
      "title": "Intro",
      "phrases": [
        [4],
        [{ "structure": "Derecho", "beats": 4, "offset": 4 }, 8, 8, 8]
      ]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4]
    },
    {
      "title": "Mambo",
      "structure": "Derecho",
      "phrases": [2]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4]
    },
    {
      "title": "Pre-Chorus",
      "structure": "Derecho",
      "phrases": [4]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [1, [8, 8, 8, 4]]
    },
    {
      "title": "Mambo",
      "phrases": [
        [
          "Derecho",
          4,
          { "structure": "Majao", "beats": 4, "offset": 4 },
          8,
          "Derecho",
          8,
          4
        ]
      ]
    },
    {
      "title": "Pre-Chorus",
      "structure": "Derecho",
      "phrases": [4]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [1, [8, 8, 8, 4]]
    },
    {
      "title": "Mambo",
      "structure": "Derecho",
      "phrases": [6]
    },
    {
      "title": "Bridge",
      "structure": "Derecho",
      "phrases": [2, 4]
    },
    {
      "title": "Mambo",
      "structure": "Derecho",
      "phrases": [[8, 4]]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [[8, 8, 8, 4], [2]]
    }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/babalu/breakdown.json
{
  "trim": 0.09,
  "beatsPerMeasure": 8,
  "tracks": [
    "Vocals",
    {
      "title": "Bongo &amp; Gu&iuml;ra",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Percussion",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Kick Drum",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Bass Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Rhythm Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Lead Guitar",
      "groups": "Guitars"
    },
    "keys &amp; Strings"
  ],
  "sections": [
    { "title": "Intro", "phrases": [4] },
    { "title": "Verse", "phrases": [4, 4] },
    {
      "title": "Chorus",
      "phrases": [
        ["Derecho", 8, 8, 8],
        ["Majao", 8, 8, 8]
      ]
    },
    { "title": "Verse", "phrases": [4] },
    { "title": "Mambo", "structure": "Majao", "phrases": [4, 4] },
    { "title": "Verse", "structure": "Derecho", "phrases": [4, 4] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4, 4] },
    { "title": "Breakdown", "phrases": [4] },
    { "title": "Bridge", "structure": "Derecho", "phrases": [4] },
    { "title": "Breakdown", "phrases": [4] },
    {
      "title": "Chorus",
      "phrases": [
        ["Derecho", 8, 8, 8],
        ["Majao", 8, 8, 8]
      ]
    },
    { "title": "Outro", "phrases": [4] }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/besitoabesito/breakdown.json
{
  "lag": 0.7,
  "trim": 0,
  "beatsPerMeasure": 8,
  "tracks": [
    { "title": "Vocals", "groups": ["Vocals"] },
    { "title": "Bongo, Gu&iuml;a &amp; Kick", "groups": ["Percussion"] },
    { "title": "Bass Guitar", "groups": ["Guitars"] },
    { "title": "Lead &amp; Rhythm Guitars", "groups": ["Guitars"] }
  ],
  "sections": [
    {
      "title": "Intro",
      "phrases": [
        ["Derecho", 8, 8, 8],
        ["Majao", 8]
      ]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4, [8, 8, 4]]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [2, [8, 4]]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [[8, 8, 8, 8, 4]]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [2, [8, 4]]
    },
    {
      "title": "Mambo",
      "structure": "Derecho",
      "phrases": [2, 2]
    },
    {
      "title": "Mambo",
      "structure": "Majao",
      "phrases": [2, 2]
    },
    {
      "title": "Mambo",
      "structure": "Majao",
      "phrases": [4]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [4, [8, 8, 4]]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [2, [8, 4]]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [[8, 8, 8, 8, 4]]
    },
    {
      "title": "Chorus",
      "structure": "Majao",
      "phrases": [2, 2, [8, 4]]
    },
    {
      "title": "Outro",
      "structure": "Derecho",
      "phrases": [[8, 4], 1]
    }
  ]
}
