=== SalsaAddict/emusicality2022/src/schema/iBreakdown.json
{
    "$ref": "#/definitions/IBreakdown",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "IBreakdown": {
            "additionalProperties": false,
            "properties": {
                "beatsPerMeasure": {
                    "title": "beatsPerMeasure",
                    "type": "number"
                },
                "lag": {
                    "title": "lag",
                    "type": "number"
                },
                "sections": {
                    "items": {
                        "$ref": "#/definitions/ISection"
                    },
                    "title": "sections",
                    "type": "array"
                },
                "tracks": {
                    "$ref": "#/definitions/ITracks",
                    "title": "tracks"
                },
                "trim": {
                    "title": "trim",
                    "type": "number"
                }
            },
            "required": [
                "beatsPerMeasure",
                "sections",
                "tracks"
            ],
            "title": "IBreakdown",
            "type": "object"
        },
        "IMeasure": {
            "additionalProperties": false,
            "properties": {
                "beats": {
                    "title": "beats",
                    "type": "number"
                },
                "offset": {
                    "title": "offset",
                    "type": "number"
                },
                "structure": {
                    "title": "structure",
                    "type": "string"
                }
            },
            "title": "IMeasure",
            "type": "object"
        },
        "IPhrase": {
            "anyOf": [
                {
                    "items": {
                        "anyOf": [
                            {
                                "$ref": "#/definitions/IMeasure"
                            },
                            {
                                "type": [
                                    "string",
                                    "number"
                                ]
                            }
                        ]
                    },
                    "type": "array"
                },
                {
                    "type": "number"
                }
            ],
            "title": "IPhrase"
        },
        "ISection": {
            "additionalProperties": false,
            "properties": {
                "phrases": {
                    "items": {
                        "$ref": "#/definitions/IPhrase"
                    },
                    "title": "phrases",
                    "type": "array"
                },
                "structure": {
                    "title": "structure",
                    "type": "string"
                },
                "title": {
                    "title": "title",
                    "type": "string"
                }
            },
            "required": [
                "phrases",
                "title"
            ],
            "title": "ISection",
            "type": "object"
        },
        "ITrack": {
            "additionalProperties": false,
            "properties": {
                "groups": {
                    "anyOf": [
                        {
                            "items": {
                                "type": "string"
                            },
                            "type": "array"
                        },
                        {
                            "type": "string"
                        }
                    ],
                    "title": "groups"
                },
                "title": {
                    "title": "title",
                    "type": "string"
                },
                "trim": {
                    "title": "trim",
                    "type": "number"
                }
            },
            "required": [
                "title"
            ],
            "title": "ITrack",
            "type": "object"
        },
        "ITrackType": {
            "anyOf": [
                {
                    "$ref": "#/definitions/ITrack"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ITrackType"
        },
        "ITracks": {
            "anyOf": [
                {
                    "items": {
                        "$ref": "#/definitions/ITrackType"
                    },
                    "type": "array"
                },
                {
                    "type": "string"
                }
            ],
            "title": "ITracks"
        }
    }
}

=== SalsaAddict/emusicality2022/src/assets/songs/meemborrachare/breakdown.json
{
  "beatsPerMeasure": 8,
  "trim": 0.25,
  "tracks": [
    "Gu&iuml;ra",
    "Bongos",
    "Bass",
    { "title": "Segunda", "trim": 2.1 },
    { "title": "Requinto", "trim": 1.4 }
  ],
  "sections": [
    { "title": "Intro", "phrases": [[4], [8, 8, 8, 8]] },
    { "title": "Verse", "structure": "Derecho", "phrases": [4] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4] },
    { "title": "Interlude", "structure": "Derecho", "phrases": [4] },
    { "title": "Verse", "structure": "Derecho", "phrases": [4] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4] },
    {
      "title": "Bridge",
      "structure": "Derecho",
      "phrases": [[{}, "Majao"]]
    },
    { "title": "Chorus", "structure": "Majao", "phrases": [4] },
    { "title": "Mambo", "structure": "Majao", "phrases": [4] },
    { "title": "Breakdown", "structure": "Urban", "phrases": [4, [4]] },
    { "title": "Chorus", "structure": "Majao", "phrases": [4] },
    {
      "title": "Bridge",
      "structure": "Derecho",
      "phrases": [[{}, "Majao"]]
    },
    { "title": "Chorus", "structure": "Majao", "phrases": [4] },
    { "title": "Ending", "phrases": [[4]] }
  ]
}

=== SalsaAddict/emusicality2022/src/assets/songs/esoesamor/breakdown.json
{
  "trim": 1.8,
  "beatsPerMeasure": 8,
  "tracks": [
    "Vocals",
    {
      "title": "Bongos",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Gu&iuml;ra",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Kick Drum",
      "groups": ["Percussion", "Rhythm"]
    },
    {
      "title": "Bass Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Rhythm Guitar",
      "groups": ["Guitars", "Rhythm"]
    },
    {
      "title": "Lead Guitar",
      "groups": "Guitars"
    }
  ],
  "sections": [
    {
      "title": "Intro",
      "phrases": [[8, 8, 4]]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8]
      ]
    },
    {
      "title": "Pre Chorus",
      "phrases": [[8, 8, 4]]
    },
    {
      "title": "Chorus",
      "phrases": [
        ["Majao", 8, "Derecho", 8],
        ["Majao", 8, "Derecho", 8]
      ]
    },
    {
      "title": "Verse",
      "structure": "Derecho",
      "phrases": [
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8]
      ]
    },
    {
      "title": "Pre Chorus",
      "phrases": [[8, 8, 4]]
    },
    {
      "title": "Chorus",
      "phrases": [
        ["Majao", 8, "Derecho", 8],
        ["Majao", 8, "Derecho", 8]
      ]
    },
    {
      "title": "Mambo",
      "phrases": [
        ["Derecho", 4],
        [8, 8],
        ["Majao", 8, 4],
        [8, 8, 4]
      ]
    },
    {
      "title": "Bridge",
      "structure": "Derecho",
      "phrases": [[8, 8, 8, 8, 4]]
    },
    {
      "title": "Chorus",
      "phrases": [
        ["Majao", 8, "Derecho", 8],
        ["Majao", 8, "Derecho", 4]
      ]
    },
    {
      "title": "Outro",
      "phrases": [[8, 1]]
    }
  ]
}
